### ISSUE TITLE
pipeline fails when parameter trim = false 

### ISSUE THREAD

**Issue by craigwindellatqut** [nf-core/bactmap#55]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/bactmap pipeline documentation](https://nf-co.re/bactmap/usage)

## Description of the bug

When setting trim = false, the pipeline stops with the error:

```
Jun-27 17:04:36.559 [main] ERROR nextflow.cli.Launcher - Access to 'FASTP.out' is undefined since the process 'FASTP' has not been invoked before accessing the output attribute
nextflow.exception.ScriptRuntimeException: Access to 'FASTP.out' is undefined since the process 'FASTP' has not been invoked before accessing the output attribute
```

## Steps to reproduce

Steps to reproduce the behaviour:

1. nextflow run  nf-core/bactmap -profile singularity
2. nextflow.config

```
...
    trim       = false
...
```

3. See error:  as above

## Expected behaviour

When using already trimmed samples, we should be able to run bactmap with trim = false

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline

```
#!/bin/bash -l
#PBS -N bactmaptest
#PBS -l select=1:ncpus=2:mem=5gb
#PBS -l walltime=168:00:00

cd $PBS_O_WORKDIR
module load java
NXF_OPTS='-Xms1g -Xmx4g'

nextflow run nf-core/bactmap -profile singularity
```
- [ ] nextflow.config
```
params {
    max_memory = '2.GB'
    max_cpus   = 2
    max_time   = '1.h'
    rapidnj    = true
    fasttree   = true
    iqtree     = true
    raxmlng    = true
    trim       = false
    input      = 'samplesheet.csv'
    reference  = 'NCTC13799.fna'
}
```

- [ ] The `.nextflow.log` file 
```
Jun-27 17:04:21.420 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/bactmap -profile singularity
Jun-27 17:04:21.547 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.4
Jun-27 17:04:23.140 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/windell/.nextflow/assets/nf-core/bactmap/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/bactmap.git
Jun-27 17:04:23.161 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/windell/.nextflow/assets/nf-core/bactmap/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/bactmap.git
Jun-27 17:04:24.570 [main] DEBUG nextflow.config.ConfigBuilder - Found config home: /home/windell/.nextflow/config
Jun-27 17:04:24.570 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/windell/.nextflow/assets/nf-core/bactmap/nextflow.config
Jun-27 17:04:24.572 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/nextflow.config
Jun-27 17:04:24.573 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/windell/.nextflow/config
Jun-27 17:04:24.573 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/windell/.nextflow/assets/nf-core/bactmap/nextflow.config
Jun-27 17:04:24.573 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/nextflow.config
Jun-27 17:04:24.579 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jun-27 17:04:24.671 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jun-27 17:04:25.275 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Jun-27 17:04:25.291 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-27 17:04:25.292 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-27 17:04:25.295 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jun-27 17:04:25.312 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Jun-27 17:04:25.611 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jun-27 17:04:25.652 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, ifb_core, denbi_qbic, genotoul, alice, mjolnir_globe, uppmax, abims, nihbiowulf, nu_genomics, oist, sahmri, mpcdf, leicester, lugh, vsc_ugent, sage, cambridge, unibe_ibu, vai, podman, czbiohub_aws, jax, cheaha, ccga_med, test, google, computerome, seg_globe, sanger, pasteur, test_full, eddie, azurebatch, bi, bigpurple, cedars, docker, gis, eva, utd_ganymede, charliecloud, fgcz, conda, singularity, icr_davros, munin, rosalind, prince, hasta, hebbe, cfc, utd_sysbio, uzh, debug, genouest, cbe, ebc, ccga_dx, crick, marvin, phoenix, biohpc_gen, shifter, awsbatch, uct_hpc, imperial, maestro, aws_tower, binac]
Jun-27 17:04:25.721 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Jun-27 17:04:25.722 [main] INFO  nextflow.cli.CmdRun - Launching `https://github.com/nf-core/bactmap` [peaceful_bhaskara] DSL2 - revision: e83f8c5f0e [master]
Jun-27 17:04:25.723 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/windell/.nextflow/plugins; core-plugins: nf-amazon@1.7.2,nf-azure@0.13.2,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
Jun-27 17:04:25.727 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jun-27 17:04:25.768 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-27 17:04:25.768 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-27 17:04:25.770 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jun-27 17:04:25.780 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jun-27 17:04:25.780 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-tower version: 1.4.0
Jun-27 17:04:25.808 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-tower@1.4.0' resolved
Jun-27 17:04:25.808 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-tower@1.4.0'
Jun-27 17:04:26.133 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-tower@1.4.0
Jun-27 17:04:26.278 [main] DEBUG nextflow.Session - Session uuid: 102eada9-1cd2-4eab-99eb-61fa2212febc
Jun-27 17:04:26.278 [main] DEBUG nextflow.Session - Run name: peaceful_bhaskara
Jun-27 17:04:26.279 [main] DEBUG nextflow.Session - Executor pool size: 2
Jun-27 17:04:26.293 [main] DEBUG nextflow.config.ConfigBuilder - Found config home: /home/windell/.nextflow/config
Jun-27 17:04:26.293 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/windell/.nextflow/assets/nf-core/bactmap/nextflow.config
Jun-27 17:04:26.293 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/nextflow.config
Jun-27 17:04:26.293 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/windell/.nextflow/config
Jun-27 17:04:26.293 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/windell/.nextflow/assets/nf-core/bactmap/nextflow.config
Jun-27 17:04:26.293 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/nextflow.config
Jun-27 17:04:26.294 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jun-27 17:04:26.346 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jun-27 17:04:26.779 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jun-27 17:04:26.803 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, ifb_core, denbi_qbic, genotoul, alice, mjolnir_globe, uppmax, abims, nihbiowulf, nu_genomics, oist, sahmri, mpcdf, leicester, lugh, vsc_ugent, sage, cambridge, unibe_ibu, vai, podman, czbiohub_aws, jax, cheaha, ccga_med, test, google, computerome, seg_globe, sanger, pasteur, test_full, eddie, azurebatch, bi, bigpurple, cedars, docker, gis, eva, utd_ganymede, charliecloud, fgcz, conda, singularity, icr_davros, munin, rosalind, prince, hasta, hebbe, cfc, utd_sysbio, uzh, debug, genouest, cbe, ebc, ccga_dx, crick, marvin, phoenix, biohpc_gen, shifter, awsbatch, uct_hpc, imperial, maestro, aws_tower, binac]
Jun-27 17:04:26.852 [main] DEBUG nextflow.cli.CmdRun -
  Version: 22.04.4 build 5706
  Created: 19-06-2022 20:51 UTC (20-06-2022 06:51 AEDT)
  System: Linux 4.12.14-122.121-default
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.2+9
  Encoding: UTF-8 (UTF-8)
  Process: 7733@cl4n058 [10.13.1.8]
  CPUs: 2 - Mem: 377.2 GB (154.8 GB) - Swap: 2 GB (1.8 GB)
Jun-27 17:04:26.914 [main] DEBUG nextflow.Session - Work-dir: /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/work [nfs]
Jun-27 17:04:26.935 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jun-27 17:04:26.949 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jun-27 17:04:26.975 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Jun-27 17:04:27.491 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jun-27 17:04:27.513 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 3; maxThreads: 1000
Jun-27 17:04:27.782 [main] DEBUG nextflow.Session - Session start invoked
Jun-27 17:04:27.786 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/results/pipeline_info/execution_trace_2022-06-27_17-04-25.txt
Jun-27 17:04:27.875 [main] DEBUG io.seqera.tower.plugin.TowerClient - Creating Tower observer -- endpoint=https://nftower.qut.edu.au/api; requestInterval=1s; aliveInterval=1m; maxRetries=5; backOffBase=3; backOffDelay=250
Jun-27 17:04:27.997 [main] DEBUG nextflow.Session - Using default localLib path: /home/windell/.nextflow/assets/nf-core/bactmap/lib
Jun-27 17:04:28.008 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/windell/.nextflow/assets/nf-core/bactmap/lib
Jun-27 17:04:28.009 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/windell/.nextflow/assets/nf-core/bactmap/lib/nfcore_external_java_deps.jar
Jun-27 17:04:29.524 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jun-27 17:04:29.931 [main] INFO  nextflow.Nextflow -

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/bactmap v1.0.0
------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : peaceful_bhaskara
  containerEngine: singularity
  launchDir      : /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01
  workDir        : /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/work
  projectDir     : /home/windell/.nextflow/assets/nf-core/bactmap
  userName       : windell
  profile        : singularity
  configFiles    : /home/windell/.nextflow/config, /home/windell/.nextflow/assets/nf-core/bactmap/nextflow.config, /mnt/work/eresearch_bio/nextflow/nf-core/bactmap/testdata/run01/nextflow.config

Input/output options
  input          : samplesheet.csv

Compulsory parameters
  reference      : NCTC13799.fna

Optional pipeline steps
  trim           : false
  adapter_file   : /home/windell/.nextflow/assets/nf-core/bactmap/assets/adapters.fas
  rapidnj        : true
  fasttree       : true
  iqtree         : true
  raxmlng        : true

Max job request options
  max_cpus       : 2
  max_memory     : 2.GB
  max_time       : 1.h

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/bactmap for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/bactmap/blob/master/CITATIONS.md
------------------------------------------------------
Jun-27 17:04:35.850 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:35.850 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:35.860 [main] DEBUG nextflow.executor.Executor - [warm up] executor > pbspro
Jun-27 17:04:35.865 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'pbspro' > capacity: 100; pollInterval: 5s; dumpInterval: 5m
Jun-27 17:04:35.869 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'pbspro' > queue-stat-interval: 1m
Jun-27 17:04:36.035 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_high` matches labels `process_high` for process with name NFCORE_BACTMAP:BACTMAP:BWA_INDEX
Jun-27 17:04:36.035 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:BWA_INDEX` matches process NFCORE_BACTMAP:BACTMAP:BWA_INDEX
Jun-27 17:04:36.048 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.048 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.076 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:SUB_SAMPLING:MASH_SKETCH
Jun-27 17:04:36.078 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.078 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.107 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches labels `process_low` for process with name NFCORE_BACTMAP:BACTMAP:SUB_SAMPLING:RASUSA
Jun-27 17:04:36.108 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.108 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.184 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:BWA_MEM
Jun-27 17:04:36.186 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.188 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.205 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:BAM_SORT_SAMTOOLS:SAMTOOLS_SORT
Jun-27 17:04:36.205 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:SAMTOOLS_SORT` matches process NFCORE_BACTMAP:BACTMAP:BAM_SORT_SAMTOOLS:SAMTOOLS_SORT
Jun-27 17:04:36.206 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.206 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.214 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches labels `process_low` for process with name NFCORE_BACTMAP:BACTMAP:BAM_SORT_SAMTOOLS:SAMTOOLS_INDEX
Jun-27 17:04:36.216 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.216 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.232 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches labels `process_low` for process with name NFCORE_BACTMAP:BACTMAP:BAM_SORT_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_STATS
Jun-27 17:04:36.233 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.234 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.250 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches labels `process_low` for process with name NFCORE_BACTMAP:BACTMAP:BAM_SORT_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_FLAGSTAT
Jun-27 17:04:36.250 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.250 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.258 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches labels `process_low` for process with name NFCORE_BACTMAP:BACTMAP:BAM_SORT_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_IDXSTATS
Jun-27 17:04:36.261 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.261 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.278 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:VARIANTS_BCFTOOLS:BCFTOOLS_MPILEUP
Jun-27 17:04:36.279 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.279 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.285 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:VARIANTS_BCFTOOLS:BCFTOOLS_FILTER
Jun-27 17:04:36.285 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.286 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.301 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches labels `process_low` for process with name NFCORE_BACTMAP:BACTMAP:VCF2PSEUDOGENOME
Jun-27 17:04:36.303 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.303 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.320 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches labels `process_low` for process with name NFCORE_BACTMAP:BACTMAP:ALIGNPSEUDOGENOMES
Jun-27 17:04:36.323 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.324 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.339 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:SNPSITES
Jun-27 17:04:36.341 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.341 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.351 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:CREATE_PHYLOGENY:RAPIDNJ
Jun-27 17:04:36.352 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.352 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.363 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:CREATE_PHYLOGENY:FASTTREE
Jun-27 17:04:36.363 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.363 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.373 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_BACTMAP:BACTMAP:CREATE_PHYLOGENY:IQTREE
Jun-27 17:04:36.374 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.374 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.379 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_high` matches labels `process_high,process_long` for process with name NFCORE_BACTMAP:BACTMAP:CREATE_PHYLOGENY:RAXMLNG
Jun-27 17:04:36.379 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_long` matches labels `process_high,process_long` for process with name NFCORE_BACTMAP:BACTMAP:CREATE_PHYLOGENY:RAXMLNG
Jun-27 17:04:36.379 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.379 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.396 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: pbspro
Jun-27 17:04:36.396 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'pbspro'
Jun-27 17:04:36.469 [main] DEBUG nextflow.Session - Session aborted -- Cause: Access to 'FASTP.out' is undefined since the process 'FASTP' has not been invoked before accessing the output attribute
Jun-27 17:04:36.507 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] splitCsv
  [operator] map
  [operator] map
  [operator] combine
  [operator] ifEmpty
  [operator] mix
  [operator] ifEmpty
  [operator] mix
  [operator] join
  [operator] ifEmpty
  [operator] mix
  [operator] ifEmpty
  [operator] mix
  [operator] map
  [operator] collect
  [operator] branch
  [operator] view
  [operator] map
  [operator] ifEmpty
  [operator] mix
  [operator] ifEmpty
  [operator] mix
  [operator] ifEmpty
  [operator] mix
  [operator] ifEmpty
  [operator] mix
  [operator] ifEmpty
  [operator] mix
  [operator] map
  [operator] collect
  [operator] collect
  [operator] ifEmpty
  [operator] collect
  [operator] collectFile

Jun-27 17:04:36.559 [main] ERROR nextflow.cli.Launcher - Access to 'FASTP.out' is undefined since the process 'FASTP' has not been invoked before accessing the output attribute
nextflow.exception.ScriptRuntimeException: Access to 'FASTP.out' is undefined since the process 'FASTP' has not been invoked before accessing the output attribute
        at nextflow.script.ProcessDef.getOut(ProcessDef.groovy:153)
        at jdk.internal.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:85)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
        at Script_c99ee09b$_runScript_closure1$_closure3.doCall(Script_c99ee09b:230)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:205)
        at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:189)
        at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
        at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
        at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:94)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at Script_14934cd2$_runScript_closure1$_closure3.doCall(Script_14934cd2:34)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:205)
        at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:189)
        at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
        at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
        at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:94)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at Script_14934cd2$_runScript_closure2$_closure4.doCall(Script_14934cd2:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:205)
        at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:189)
        at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
        at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:208)
        at nextflow.script.BaseScript.run(BaseScript.groovy:217)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:220)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:337)
        at nextflow.cli.Launcher.run(Launcher.groovy:480)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)
Jun-27 17:04:36.601 [Actor Thread 6] DEBUG nextflow.file.SortFileCollector - FileCollector temp dir not removed: null
```

## System

- Hardware: HPC
- Executor: PBSPRO
- OS: SUSE
- Version 12

## Nextflow Installation

- Version: 22.04.4

## Container engine

- Engine: singularity
- version: 3.9.8-1

**Comment by adamd3** [comment]
I got the same error. It is caused by the `MULTIQC` process attempting to access the output from FASTP (which has not been run because trimming was off).

The MULTIQC process cannot currently be switched off (even when `--skip_multiqc true` is provided).

A simple fix would be to turn off MultiQC when trimming is disabled, or to run it without the FASTP output.

**Comment by jacquikeane** [comment]
I am experiencing the same issue. Any plans to add a fix to allow the pipeline to be run without the trimming/fastp step?
